replicaCount: 1

image:
  repository: acrdevopslab99d7904d.azurecr.io/my-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: azure/application-gateway
  host: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  APP_ENV: "dev"
  LOG_LEVEL: "info"
