management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.endpoint.prometheus.enabled=true
spring.application.name=my-app
